version: '3.8'  # Използвайте по-нова версия
services:
  app:
    image: kirito3/student_registry:${TAG:-latest}
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=production
    restart: unless-stopped  # Добавете автоматичен рестарт